# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				snowball = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				ender_pearl = true
				zombie = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				wither_skull = true
				eye_of_ender = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				block_display = true
				elder_guardian = true
				chest_boat = true
				small_fireball = true
				boat = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				wither_skeleton = true
				salmon = true
				wandering_trader = true
				vex = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				warden = true
				glow_squid = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				sniffer = true
				chicken = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				ominous_item_spawner = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.fallingtrees]
				tree = true

			[light_sources.settings.entities.simplyswords]
				battlestandard = true
				livyatan_entity = true
				frostfall_entity = true
				simplybeeentity = true
				battlestandarddark = true
				thrown_sword = true
				simplyaxolotlentity = true
				runic_entity = true
				spear_entity = true

			[light_sources.settings.entities.gobber2]
				gobber2_arrow_end = true
				gobber2_arrow = true
				gobber2_arrow_nether = true

			[light_sources.settings.entities.gravestones]
				gravestone_skeleton = true

			[light_sources.settings.entities.amendments]
				medium_dragon_fireball = true
				falling_lantern = true
				medium_fireball = true

			[light_sources.settings.entities.smallships]
				ground_cannon = true
				galley = true
				brigg = true
				drakkar = true
				cog = true
				cannon_ball = true

			[light_sources.settings.entities.immersive_aircraft]
				cargo_airship = true
				airship = true
				bamboo_hopper = true
				warship = true
				gyrodyne = true
				quadrocopter = true
				biplane = true
				tiny_tnt = true
				bullet = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				brick_projectile = true
				falling_sack = true
				pearl_marker = true
				hat_stand = true
				bomb = true
				falling_ash = true
				cannonball = true
				falling_urn = true
				red_merchant = true
				cannon_boat = true
				rope_arrow = true
				slimeball_projectile = true

			[light_sources.settings.entities.mythicmetals]
				banglum_tnt_minecart = true
				star_platinum_arrow = true
				runite_arrow = true
				banglum_tnt = true
				banglum_nuke = true
				palladium_minecart = true

			[light_sources.settings.entities.decocraft]
				seat = true

			[light_sources.settings.entities.artifacts]
				mimic = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
